[package]
authors = ["Cole Lawrence <cole@colelawrence.com>"]
edition = "2018"
name = "shipyard_app"
version = "0.1.0"

[dependencies]
shipyard = {version = "*", path = "../shipyard", features = [], default-features = false}
tracing = "0.1"

[dev-dependencies]
tracing-subscriber = {version = "0.2", features = ["chrono", "env-filter", "fmt"]}
